/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Earth(props) {
  const { nodes, materials } = useGLTF('/models/tripo_pbr_model_54ebe6a9-539a-4bd5-a2d9-60ad07e04725.glb')
  return (
    <group {...props} dispose={null} scale={[40,40,40]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_54ebe6a9-539a-4bd5-a2d9-60ad07e04725'].geometry}
        material={materials['tripo_material_54ebe6a9-539a-4bd5-a2d9-60ad07e04725']}
      />
    </group>
  )
}

useGLTF.preload('/models/tripo_pbr_model_54ebe6a9-539a-4bd5-a2d9-60ad07e04725.glb')
