/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mars(props) {
  const { nodes, materials } = useGLTF('/models/tripo_pbr_model_62a9908c-ed0f-4e21-af2c-a4528db51cb9.glb')
  return (
    <group {...props} dispose={null} scale={[40,40,40]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_62a9908c-ed0f-4e21-af2c-a4528db51cb9'].geometry}
        material={materials['tripo_material_62a9908c-ed0f-4e21-af2c-a4528db51cb9']}
      />
    </group>
  )
}

useGLTF.preload('/models/tripo_pbr_model_62a9908c-ed0f-4e21-af2c-a4528db51cb9.glb')