/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Mercury(props) {
  const { nodes, materials } = useGLTF('/models/tripo_pbr_model_cdda7fe6-dbb0-438c-afa7-8a70d50b45be.glb')
  return (
    <group {...props} dispose={null} scale={[20,20,20]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_cdda7fe6-dbb0-438c-afa7-8a70d50b45be'].geometry}
        material={materials['tripo_material_cdda7fe6-dbb0-438c-afa7-8a70d50b45be']}
      />
    </group>
  )
}

useGLTF.preload('/models/tripo_pbr_model_cdda7fe6-dbb0-438c-afa7-8a70d50b45be.glb')
