


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Neptune(props) {
  const { nodes, materials } = useGLTF('/models/tripo_pbr_model_28b97df5-b1b6-467c-a1f5-6606bfcbef94.glb')
  return (
    <group {...props} dispose={null} scale={[60,60,60]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_28b97df5-b1b6-467c-a1f5-6606bfcbef94'].geometry}
        material={materials['tripo_material_28b97df5-b1b6-467c-a1f5-6606bfcbef94']}
      />
    </group>
  )
}

useGLTF.preload('/models/tripo_pbr_model_28b97df5-b1b6-467c-a1f5-6606bfcbef94.glb')