/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Saturn(props) {
  const { nodes, materials } = useGLTF('/models/tripo_pbr_model_a7a03855-5696-49dc-9ebe-c1b18551bed4.glb')
  return (
    <group {...props} dispose={null} scale={[80,80,80]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_a7a03855-5696-49dc-9ebe-c1b18551bed4'].geometry}
        material={materials['tripo_material_a7a03855-5696-49dc-9ebe-c1b18551bed4']}
      />
    </group>
  )
}

useGLTF.preload('/models/tripo_pbr_model_a7a03855-5696-49dc-9ebe-c1b18551bed4.glb')