/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Uranus(props) {
  const { nodes, materials } = useGLTF('/models/tripo_pbr_model_86e2120a-713a-41b8-9148-5b9cdad58ca2.glb')
  return (
    <group {...props} dispose={null} scale={[50,50,50]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_86e2120a-713a-41b8-9148-5b9cdad58ca2'].geometry}
        material={materials['tripo_material_86e2120a-713a-41b8-9148-5b9cdad58ca2']}
      />
    </group>
  )
}

useGLTF.preload('/models/tripo_pbr_model_86e2120a-713a-41b8-9148-5b9cdad58ca2.glb')