/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Venus(props) {
  const { nodes, materials } = useGLTF('/models/tripo_pbr_model_410780c7-fc76-459f-954b-59900db074b0.glb')
  return (
    <group {...props} dispose={null} scale={[30,30,30]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['tripo_node_410780c7-fc76-459f-954b-59900db074b0'].geometry}
        material={materials['tripo_material_410780c7-fc76-459f-954b-59900db074b0']}
      />
    </group>
  )
}

useGLTF.preload('/models/tripo_pbr_model_410780c7-fc76-459f-954b-59900db074b0.glb')